In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv('C:/Users/GPT BANTWAL/Downloads/food.csv') 
df

,Category,Description,Nutrient Data Bank Number,Data.Alpha Carotene,Data.Beta Carotene,Data.Beta Cryptoxanthin,Data.Carbohydrate,Data.Cholesterol,Data.Choline,Data.Fiber,...,Data.Major Minerals.Phosphorus,Data.Major Minerals.Potassium,Data.Major Minerals.Sodium,Data.Major Minerals.Zinc,Data.Vitamins.Vitamin A - RAE,Data.Vitamins.Vitamin B12,Data.Vitamins.Vitamin B6,Data.Vitamins.Vitamin C,Data.Vitamins.Vitamin E,Data.Vitamins.Vitamin K
0,Milk,"Milk, human",11000000,0,7,0,6.89,14,16.0,0.0,...,14,51,17,0.17,61,0.05,0.011,5.0,0.08,0.3
1,Milk,"Milk, NFS",11100000,0,4,0,4.87,8,17.9,0.0,...,103,157,39,0.42,59,0.56,0.060,0.1,0.03,0.2
2,Milk,"Milk, whole",11111000,0,7,0,4.67,12,17.8,0.0,...,101,150,38,0.41,32,0.54,0.061,0.0,0.05,0.3
3,Milk,"Milk, low sodium, whole",11111100,0,7,0,4.46,14,16.0,0.0,...,86,253,3,0.38,29,0.36,0.034,0.9,0.08,0.3
4,Milk,"Milk, calcium fortified, whole",11111150,0,7,0,4.67,12,17.8,0.0,...,101,150,38,0.41,32,0.54,0.061,0.0,0.05,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7078,Tomatoes as ingredient in omelet,Tomatoes as ingredient in omelet,99997802,103,464,0,5.48,0,7.4,1.6,...,30,278,6,0.21,43,0.00,0.104,18.2,0.60,8.8
7079,Other vegetables as ingredient in omelet,Other vegetables as ingredient in omelet,99997804,1,11,0,4.81,0,19.4,1.4,...,96,364,6,0.58,1,0.04,0.123,6.3,0.03,0.4
7080,Vegetables as ingredient in curry,Vegetables as ingredient in curry,99997810,368,994,0,11.60,0,14.6,2.2,...,46,312,19,0.28,98,0.00,0.177,16.2,0.24,8.9
7081,Sauce as ingredient in hamburgers,Sauce as ingredient in hamburgers,99998130,0,194,4,17.14,13,20.0,0.6,...,33,190,845,0.21,21,0.04,0.104,2.5,1.90,50.8
7082,Industrial oil as ingredient in food,Industrial oil as ingredient in food,99998210,0,0,0,0.00,0,0.2,0.0,...,0,0,0,0.01,0,0.00,0.000,0.0,10.50,155.8

In [3]:
df.isnull()

,Category,Description,Nutrient Data Bank Number,Data.Alpha Carotene,Data.Beta Carotene,Data.Beta Cryptoxanthin,Data.Carbohydrate,Data.Cholesterol,Data.Choline,Data.Fiber,...,Data.Major Minerals.Phosphorus,Data.Major Minerals.Potassium,Data.Major Minerals.Sodium,Data.Major Minerals.Zinc,Data.Vitamins.Vitamin A - RAE,Data.Vitamins.Vitamin B12,Data.Vitamins.Vitamin B6,Data.Vitamins.Vitamin C,Data.Vitamins.Vitamin E,Data.Vitamins.Vitamin K
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7078,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7079,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7080,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7081,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7082,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7083 entries, 0 to 7082
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Category                        7083 non-null   object
 1   Description                     7083 non-null   object
 2   Nutrient Data Bank Number       7083 non-null   int64
 3   Data.Alpha Carotene             7083 non-null   int64
 4   Data.Beta Carotene              7083 non-null   int64
 5   Data.Beta Cryptoxanthin         7083 non-null   int64
 6   Data.Carbohydrate               7083 non-null   float64
 7   Data.Cholesterol                7083 non-null   int64
 8   Data.Choline                    7083 non-null   float64
 9   Data.Fiber                      7083 non-null   float64
 10  Data.Lutein and Zeaxanthin      7083 non-null   int64
 11  Data.Lycopene                   7083 non-null   int64
 12  Data.Niacin                     7083 non-null   float64
 13  Data.Protein                    7083 non-null   float64
 14  Data.Retinol                    7083 non-null   int64
 15  Data.Riboflavin                 7083 non-null   float64
 16  Data.Selenium                   7083 non-null   float64
 17  Data.Sugar Total                7083 non-null   float64
 18  Data.Thiamin                    7083 non-null   float64
 19  Data.Water                      7083 non-null   float64
 20  Data.Fat.Monosaturated Fat      7083 non-null   float64
 21  Data.Fat.Polysaturated Fat      7083 non-null   float64
 22  Data.Fat.Saturated Fat          7083 non-null   float64
 23  Data.Fat.Total Lipid            7083 non-null   float64
 24  Data.Major Minerals.Calcium     7083 non-null   int64
 25  Data.Major Minerals.Copper      7083 non-null   float64
 26  Data.Major Minerals.Iron        7083 non-null   float64
 27  Data.Major Minerals.Magnesium   7083 non-null   int64
 28  Data.Major Minerals.Phosphorus  7083 non-null   int64
 29  Data.Major Minerals.Potassium   7083 non-null   int64
 30  Data.Major Minerals.Sodium      7083 non-null   int64
 31  Data.Major Minerals.Zinc        7083 non-null   float64
 32  Data.Vitamins.Vitamin A - RAE   7083 non-null   int64
 33  Data.Vitamins.Vitamin B12       7083 non-null   float64
 34  Data.Vitamins.Vitamin B6        7083 non-null   float64
 35  Data.Vitamins.Vitamin C         7083 non-null   float64
 36  Data.Vitamins.Vitamin E         7083 non-null   float64
 37  Data.Vitamins.Vitamin K         7083 non-null   float64
dtypes: float64(22), int64(14), object(2)
memory usage: 2.1+ MB

In [9]:
x=df.columns.drop('Category')
x

Index(['Description', 'Nutrient Data Bank Number', 'Data.Alpha Carotene',
       'Data.Beta Carotene', 'Data.Beta Cryptoxanthin', 'Data.Carbohydrate',
       'Data.Cholesterol', 'Data.Choline', 'Data.Fiber',
       'Data.Lutein and Zeaxanthin', 'Data.Lycopene', 'Data.Niacin',
       'Data.Protein', 'Data.Retinol', 'Data.Riboflavin', 'Data.Selenium',
       'Data.Sugar Total', 'Data.Thiamin', 'Data.Water',
       'Data.Fat.Monosaturated Fat', 'Data.Fat.Polysaturated Fat',
       'Data.Fat.Saturated Fat', 'Data.Fat.Total Lipid',
       'Data.Major Minerals.Calcium', 'Data.Major Minerals.Copper',
       'Data.Major Minerals.Iron', 'Data.Major Minerals.Magnesium',
       'Data.Major Minerals.Phosphorus', 'Data.Major Minerals.Potassium',
       'Data.Major Minerals.Sodium', 'Data.Major Minerals.Zinc',
       'Data.Vitamins.Vitamin A - RAE', 'Data.Vitamins.Vitamin B12',
       'Data.Vitamins.Vitamin B6', 'Data.Vitamins.Vitamin C',
       'Data.Vitamins.Vitamin E', 'Data.Vitamins.Vitamin K'],
      dtype='object')

In [10]:
y=df['Category']
y

0                                           Milk
1                                           Milk
2                                           Milk
3                                           Milk
4                                           Milk
                          ...
7078            Tomatoes as ingredient in omelet
7079    Other vegetables as ingredient in omelet
7080           Vegetables as ingredient in curry
7081           Sauce as ingredient in hamburgers
7082        Industrial oil as ingredient in food
Name: Category, Length: 7083, dtype: object